GET http://localhost:3333/api/product/10?title=tv

###

POST http://localhost:3333/api/product
Content-Type: application/json

{
    "id":56,
    "title":"lemon"
}

###

GET http://localhost:3333/api/test/3

###

GET http://localhost:3333/api

###
GET http://localhost:3333/api/12?title=testpipe